[tool.poetry]
name = "pixiv2bg"
version = "1.0.0"
description = "Pixiv pictures to background."
authors = ["Nasy"]
license = "MIT"

[tool.poetry.dependencies]
uvloop = "^0.11.1"
aiohttp = "^3.3"
tqdm = "^4.24"
ujson = "^1.35"

[tool.black]
line-length = 79
